### ISSUE TITLE
Pull requests시 ktlint 버그

### ISSUE THREAD

**Issue by Kongbee** [pknu-wap/2022_WAP-APP-TEAM1#40]
## Given 
- 저는 평소와 같이 `pull request`를 했습니다

## When 
- `pull request`를 하자마자 디스코드가 오더라구요!

## Then 
- `Check Code Quality failure on feature/#38`
- `GitHub Actions checks falilure on feature/#38`
- 라는 디스코드 메세지가 왔습니다
- `develop branch`와 관련이 있어보였습니다!

## 자료 첨부
![image](https://user-images.githubusercontent.com/84635035/168011655-2e137b8c-aa77-4fdb-bf5b-e8e3ad367742.png)
![image](https://user-images.githubusercontent.com/84635035/168011790-c7de6de8-c8ee-4524-aa1a-d1de1b0121ef.png)

**Comment by Cha-Ji** [comment]
지송ㅋㅋ

**Comment by Kongbee** [comment]
> 지송ㅋㅋ

괜츈 :)
